### PR TITLE
Add lua to hello-universe.sh

### PR DESCRIPTION
**Pull request by magnusviri**
This depends on https://github.com/teaxyz/pantry.extra/pull/20. And actually, I don't know how the cli decides what interpreter to run based on the file extension, so there's probably something else that needs to be done before this will work.

### CODE REVIEW

**Comment by mxcl** [comment]
> I don't know how the cli decides what interpreter to run based on the file extension, so there's probably something else that needs to be done before this will work.

Currently that needs to be added in tea/cli.

But we have a PR from @jhheider to fix that.

**Comment by jhheider** [comment]
Therefore: requires https://github.com/teaxyz/cli/pull/150 (which requires https://github.com/teaxyz/pantry.core/pull/33)

**Comment by mxcl** [comment]
https://github.com/teaxyz/cli/pull/150 merged, so now we need to add the `interprets` section to Lua’s package.yml

**Comment by pedrocruzio** [comment]
> [teaxyz/cli#150](https://github.com/teaxyz/cli/pull/150) merged, so now we need to add the `interprets` section to Lua’s package.yml

@mxcl just sent a PR to add `interprets` to the lua package.

**Comment by mxcl** [comment]
Thanks @pedrocruzio

**Pull request merged**
